# Generated by Django 6.1 on 2026-08-07 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code article')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom article')),
                ('description', models.TextField(blank=True, verbose_name='Description article')),
                ('unite_mesure', models.CharField(max_length=50, verbose_name='Unité de mesure')),
                ('seuil_minimum', models.PositiveIntegerField(default=10, help_text="Quantité minimale en stock. En dessous de ce seuil, l'article est considéré comme en stock faible.", verbose_name='Seuil minimum')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Référence')),
                ('date', models.DateField(verbose_name='Date de la demande')),
                ('statut', models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('EN_COURS', 'En cours'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='NOUVEAU', max_length=50, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Demande',
                'verbose_name_plural': 'Demandes',
            },
        ),
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code emplacement')),
                ('location', models.CharField(max_length=200, verbose_name='Emplacement')),
            ],
            options={
                'verbose_name': 'Emplacement',
                'verbose_name_plural': 'Emplacements',
            },
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code fonction')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom fonction')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Fonction',
                'verbose_name_plural': 'Fonctions',
            },
        ),
        migrations.CreateModel(
            name='TypeDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Type de demande')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Type de demande',
                'verbose_name_plural': 'Types de demande',
            },
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Référence')),
                ('date', models.DateField(verbose_name='Date du devis')),
                ('client', models.CharField(max_length=200, verbose_name='Client')),
                ('validite_jours', models.PositiveIntegerField(default=30, verbose_name='Validité (jours)')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis', to='app.demande', verbose_name='Demande associée')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BonSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Référence')),
                ('date', models.DateField(verbose_name='Date du bon de sortie')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_sortie', to='app.demande', verbose_name='Demande associée')),
                ('emplacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_sortie', to='app.emplacement', verbose_name='Emplacement')),
            ],
            options={
                'verbose_name': 'Bon de sortie',
                'verbose_name_plural': 'Bons de sortie',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BonEntree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Référence')),
                ('date', models.DateField(verbose_name="Date du bon d'entrée")),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('emplacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_entree', to='app.emplacement', verbose_name='Emplacement')),
            ],
            options={
                'verbose_name': "Bon d'entrée",
                'verbose_name_plural': "Bons d'entrée",
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LigneBonEntree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité entrée')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_bon_entree', to='app.article', verbose_name='Article')),
                ('bon_entree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='app.bonentree', verbose_name="Bon d'entrée")),
            ],
            options={
                'verbose_name': "Ligne de bon d'entrée",
                'verbose_name_plural': "Lignes de bon d'entrée",
            },
        ),
        migrations.CreateModel(
            name='LigneBonSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité sortie')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_bon_sortie', to='app.article', verbose_name='Article')),
                ('bon_sortie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='app.bonsortie', verbose_name='Bon de sortie')),
            ],
            options={
                'verbose_name': 'Ligne de bon de sortie',
                'verbose_name_plural': 'Lignes de bon de sortie',
            },
        ),
        migrations.CreateModel(
            name='LigneDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité demandée')),
                ('commentaire', models.CharField(blank=True, max_length=255, verbose_name='Commentaire')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_demande', to='app.article', verbose_name='Article')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='app.demande', verbose_name='Demande')),
            ],
            options={
                'verbose_name': 'Ligne de demande',
                'verbose_name_plural': 'Lignes de demande',
            },
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_devis', to='app.article', verbose_name='Article')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='app.devis', verbose_name='Devis')),
            ],
            options={
                'verbose_name': 'Ligne de devis',
                'verbose_name_plural': 'Lignes de devis',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('postnom', models.CharField(blank=True, max_length=100, verbose_name='Postnom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10, verbose_name='Sexe')),
                ('datenaiss', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('lieunaiss', models.CharField(blank=True, max_length=100, verbose_name='Lieu de naissance')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnels', to='app.emplacement', verbose_name='Chantier')),
                ('fonction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnels', to='app.fonction')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnels',
            },
        ),
        migrations.AddField(
            model_name='demande',
            name='demandeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='app.personnel', verbose_name='Demandeur'),
        ),
        migrations.AddField(
            model_name='bonsortie',
            name='destinataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_sortie_destinataire', to='app.personnel', verbose_name='Destinataire'),
        ),
        migrations.AddField(
            model_name='bonentree',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_entree_fournisseur', to='app.personnel', verbose_name='Fournisseur'),
        ),
        migrations.AddField(
            model_name='demande',
            name='type_demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='app.typedemande', verbose_name='Type de demande'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_disponible', models.PositiveIntegerField(default=0, verbose_name='Quantité disponible')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='app.article', verbose_name='Article')),
                ('emplacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='app.emplacement', verbose_name='Emplacement')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'constraints': [models.UniqueConstraint(fields=('article', 'emplacement'), name='unique_stock_article_emplacement')],
            },
        ),
    ]
