# Generated by Django 6.1 on 2026-08-08 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonsortie',
            name='emplacement_provenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_sortie_provenance', to='app.emplacement', verbose_name='Emplacement de provenance'),
        ),
        migrations.AlterField(
            model_name='bonsortie',
            name='emplacement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_sortie', to='app.emplacement', verbose_name='Emplacement de destination'),
        ),
    ]
