# Generated by Django 6.0.7 on 2026-08-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_personnel_chantier'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='seuil_minimum',
            field=models.PositiveIntegerField(default=10, help_text="Quantité minimale en stock. En dessous de ce seuil, l'article est considéré comme en stock faible.", verbose_name='Seuil minimum'),
        ),
    ]
