# Generated by Django 6.0.7 on 2026-08-03 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_article_seuil_minimum'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonEntree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Référence')),
                ('date', models.DateField(verbose_name="Date du bon d'entrée")),
                ('fournisseur', models.CharField(blank=True, max_length=200, verbose_name='Fournisseur')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('emplacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_entree', to='app.emplacement', verbose_name='Emplacement')),
            ],
            options={
                'verbose_name': "Bon d'entrée",
                'verbose_name_plural': "Bons d'entrée",
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BonSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Référence')),
                ('date', models.DateField(verbose_name='Date du bon de sortie')),
                ('destinataire', models.CharField(blank=True, max_length=200, verbose_name='Destinataire')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_sortie', to='app.demande', verbose_name='Demande associée')),
                ('emplacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_sortie', to='app.emplacement', verbose_name='Emplacement')),
            ],
            options={
                'verbose_name': 'Bon de sortie',
                'verbose_name_plural': 'Bons de sortie',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Référence')),
                ('date', models.DateField(verbose_name='Date du devis')),
                ('client', models.CharField(max_length=200, verbose_name='Client')),
                ('validite_jours', models.PositiveIntegerField(default=30, verbose_name='Validité (jours)')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis', to='app.demande', verbose_name='Demande associée')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LigneBonEntree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité entrée')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_bon_entree', to='app.article', verbose_name='Article')),
                ('bon_entree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='app.bonentree', verbose_name="Bon d'entrée")),
            ],
            options={
                'verbose_name': "Ligne de bon d'entrée",
                'verbose_name_plural': "Lignes de bon d'entrée",
            },
        ),
        migrations.CreateModel(
            name='LigneBonSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité sortie')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_bon_sortie', to='app.article', verbose_name='Article')),
                ('bon_sortie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='app.bonsortie', verbose_name='Bon de sortie')),
            ],
            options={
                'verbose_name': 'Ligne de bon de sortie',
                'verbose_name_plural': 'Lignes de bon de sortie',
            },
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_devis', to='app.article', verbose_name='Article')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='app.devis', verbose_name='Devis')),
            ],
            options={
                'verbose_name': 'Ligne de devis',
                'verbose_name_plural': 'Lignes de devis',
            },
        ),
    ]
