# Generated by Django 6.1 on 2026-08-07 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_bonentree_bonsortie_devis_lignebonentree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonentree',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_entree_fournisseur', to='app.personnel', verbose_name='Fournisseur'),
        ),
        migrations.AlterField(
            model_name='bonsortie',
            name='destinataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_sortie_destinataire', to='app.personnel', verbose_name='Destinataire'),
        ),
    ]
